# TelcoSec-Chisel Real-time Scheduling Priority Limits
# Allows members of the realtime group to set real-time priority (crucial for SDR transceivers)

@realtime         -       rtprio          99
@realtime         -       memlock         unlimited
