---
# Services to ensure are enabled after installation
services:
    - name: NetworkManager
      enabled: true
    - name: lightdm
      enabled: true
    - name: ssh
      enabled: false

# Targets to ensure are enabled
targets: []
